/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kodkod_engine_satlab_MiniSatProver */

#ifndef _Included_kodkod_engine_satlab_MiniSatProver
#define _Included_kodkod_engine_satlab_MiniSatProver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kodkod_engine_satlab_MiniSatProver
 * Method:    make
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_kodkod_engine_satlab_MiniSatProver_make
  (JNIEnv *, jclass);

/*
 * Class:     kodkod_engine_satlab_MiniSatProver
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_kodkod_engine_satlab_MiniSatProver_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     kodkod_engine_satlab_MiniSatProver
 * Method:    addVariables
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_kodkod_engine_satlab_MiniSatProver_addVariables
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     kodkod_engine_satlab_MiniSatProver
 * Method:    addClause
 * Signature: (J[I)Z
 */
JNIEXPORT jboolean JNICALL Java_kodkod_engine_satlab_MiniSatProver_addClause
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     kodkod_engine_satlab_MiniSatProver
 * Method:    solve
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_kodkod_engine_satlab_MiniSatProver_solve
  (JNIEnv *, jobject, jlong);

/*
 * Class:     kodkod_engine_satlab_MiniSatProver
 * Method:    valueOf
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_kodkod_engine_satlab_MiniSatProver_valueOf
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     kodkod_engine_satlab_MiniSatProver
 * Method:    trace
 * Signature: (JZ)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_kodkod_engine_satlab_MiniSatProver_trace
  (JNIEnv *, jobject, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
