#!/bin/bash

# The purpose of this script is to copy the Alloy files that we use
# but have to do some slight renaming in them
# rerun this script whenever Alloy updates these files

# /g means multiple places on line

# it's tricky when to convert to turn CompModule into DCModule (the original CompModule with renaming) 
# vs DashModule (our code, which is an extension of DCModule)

# Maintenance
# When Alloy.lex, Alloy.cup change the line numbers below will have to change!

p=../../org.alloytools.alloy.core/parser/
msg=$'/*\n * DO NOT EDIT THIS FILE\n * DASH: file copied from Alloy src with replacements for Dash - see install-alloy-files.sh \n */\n\n'


cp $p/Alloy.lex .

sed -i -e 's/package edu.mit.csail.sdg.parser/package ca.uwaterloo.watform.parser/' Alloy.lex

sed -i -e 's/CompLexer/DashLexer/g' Alloy.lex
sed -i -e 's/CompSym/DashSym/g' Alloy.lex
#sed -i -e 's/CompModule/DashModule/g' Alloy.lex

# FILE LINE NUMBER DEPENDENCE BELOW
sed -n -e '1,24p' Alloy.lex > part1.txt  # to the end of imports
sed -n -e '25,235p' Alloy.lex > part2.txt # to the end of tokens
sed -n -e '236,$p' Alloy.lex > part3.txt
{ echo "$msg"; cat part1.txt Dash-lex-imports.txt part2.txt Dash-lex-addition.txt part3.txt ; } > Dash.lex
rm Alloy.lex part*.txt 
rm *.lex-e

# --------------

cp $p/Alloy.cup .

sed -i -e 's/package edu.mit.csail.sdg.parser/package ca.uwaterloo.watform.parser/' Alloy.cup

sed -i -e 's/CompLexer/DashLexer/g' Alloy.cup
sed -i -e 's/CompSym/DashSym/g' Alloy.cup
sed -i -e 's/CompParser/DashParser/g' Alloy.cup
sed -i -e 's/CompFilter/DashFilter/g' Alloy.cup

sed -i -e 's/alloymodule/dashmodule/g' Alloy.cup
sed -i -e 's/public CompModule dashmodule=null;/public DashModule dashmodule=null;/g' Alloy.cup
sed -i -e 's/static CompModule alloy_parseStream/static DashModule alloy_parseStream/' Alloy.cup
sed -i -e 's/CompModule u = new CompModule(root, filename, prefix);/DashModule u = new DashModule(root, filename, prefix);/' Alloy.cup

# split it up and put it back together
# FILE LINE NUMBER DEPENDENCE BELOW
sed -n -e '1,61p' Alloy.cup > part1.txt # to end of imports
sed -n -e '62,247p' Alloy.cup > part2.txt # to the end of symbols
sed -n -e '248,529p' Alloy.cup > part3.txt # to end of terminals
sed -n -e '530,617p' Alloy.cup > part4.txt # to end of nonterminals
sed -n -e '618,$p' Alloy.cup > part5.txt # to end of file
{ echo "$msg"; cat part1.txt Dash-cup-imports.txt part2.txt Dash-cup-symbols.txt part3.txt Dash-cup-terminals.txt part4.txt Dash-cup-nonterminals.txt part5.txt Dash-cup-grammar.txt; } > Dash.cup
rm Alloy.cup part*.txt
rm *.cup-e




