module tests/test

abstract sig A {}
one sig X,Y extends A {}

check { X->X-X->X in A -> A } for 2 expect 0
check { X->X-X->X in A ->some A } for 2 expect 1
check { X->X-X->X in A ->lone A } for 2 expect 0
check { X->X-X->X in A ->one A } for 2 expect 1
check { X->X-X->X in A some-> A } for 2 expect 1
check { X->X-X->X in A some->some A } for 2 expect 1
check { X->X-X->X in A some->lone A } for 2 expect 1
check { X->X-X->X in A some->one A } for 2 expect 1
check { X->X-X->X in A lone-> A } for 2 expect 0
check { X->X-X->X in A lone->some A } for 2 expect 1
check { X->X-X->X in A lone->lone A } for 2 expect 0
check { X->X-X->X in A lone->one A } for 2 expect 1
check { X->X-X->X in A one-> A } for 2 expect 1
check { X->X-X->X in A one->some A } for 2 expect 1
check { X->X-X->X in A one->lone A } for 2 expect 1
check { X->X-X->X in A one->one A } for 2 expect 1
check { X->X in A -> A } for 2 expect 0
check { X->X in A ->some A } for 2 expect 1
check { X->X in A ->lone A } for 2 expect 0
check { X->X in A ->one A } for 2 expect 1
check { X->X in A some-> A } for 2 expect 1
check { X->X in A some->some A } for 2 expect 1
check { X->X in A some->lone A } for 2 expect 1
check { X->X in A some->one A } for 2 expect 1
check { X->X in A lone-> A } for 2 expect 0
check { X->X in A lone->some A } for 2 expect 1
check { X->X in A lone->lone A } for 2 expect 0
check { X->X in A lone->one A } for 2 expect 1
check { X->X in A one-> A } for 2 expect 1
check { X->X in A one->some A } for 2 expect 1
check { X->X in A one->lone A } for 2 expect 1
check { X->X in A one->one A } for 2 expect 1
check { X->Y in A -> A } for 2 expect 0
check { X->Y in A ->some A } for 2 expect 1
check { X->Y in A ->lone A } for 2 expect 0
check { X->Y in A ->one A } for 2 expect 1
check { X->Y in A some-> A } for 2 expect 1
check { X->Y in A some->some A } for 2 expect 1
check { X->Y in A some->lone A } for 2 expect 1
check { X->Y in A some->one A } for 2 expect 1
check { X->Y in A lone-> A } for 2 expect 0
check { X->Y in A lone->some A } for 2 expect 1
check { X->Y in A lone->lone A } for 2 expect 0
check { X->Y in A lone->one A } for 2 expect 1
check { X->Y in A one-> A } for 2 expect 1
check { X->Y in A one->some A } for 2 expect 1
check { X->Y in A one->lone A } for 2 expect 1
check { X->Y in A one->one A } for 2 expect 1
check { X->Y+X->X in A -> A } for 2 expect 0
check { X->Y+X->X in A ->some A } for 2 expect 1
check { X->Y+X->X in A ->lone A } for 2 expect 1
check { X->Y+X->X in A ->one A } for 2 expect 1
check { X->Y+X->X in A some-> A } for 2 expect 0
check { X->Y+X->X in A some->some A } for 2 expect 1
check { X->Y+X->X in A some->lone A } for 2 expect 1
check { X->Y+X->X in A some->one A } for 2 expect 1
check { X->Y+X->X in A lone-> A } for 2 expect 0
check { X->Y+X->X in A lone->some A } for 2 expect 1
check { X->Y+X->X in A lone->lone A } for 2 expect 1
check { X->Y+X->X in A lone->one A } for 2 expect 1
check { X->Y+X->X in A one-> A } for 2 expect 0
check { X->Y+X->X in A one->some A } for 2 expect 1
check { X->Y+X->X in A one->lone A } for 2 expect 1
check { X->Y+X->X in A one->one A } for 2 expect 1
check { Y->X in A -> A } for 2 expect 0
check { Y->X in A ->some A } for 2 expect 1
check { Y->X in A ->lone A } for 2 expect 0
check { Y->X in A ->one A } for 2 expect 1
check { Y->X in A some-> A } for 2 expect 1
check { Y->X in A some->some A } for 2 expect 1
check { Y->X in A some->lone A } for 2 expect 1
check { Y->X in A some->one A } for 2 expect 1
check { Y->X in A lone-> A } for 2 expect 0
check { Y->X in A lone->some A } for 2 expect 1
check { Y->X in A lone->lone A } for 2 expect 0
check { Y->X in A lone->one A } for 2 expect 1
check { Y->X in A one-> A } for 2 expect 1
check { Y->X in A one->some A } for 2 expect 1
check { Y->X in A one->lone A } for 2 expect 1
check { Y->X in A one->one A } for 2 expect 1
check { Y->X+X->X in A -> A } for 2 expect 0
check { Y->X+X->X in A ->some A } for 2 expect 0
check { Y->X+X->X in A ->lone A } for 2 expect 0
check { Y->X+X->X in A ->one A } for 2 expect 0
check { Y->X+X->X in A some-> A } for 2 expect 1
check { Y->X+X->X in A some->some A } for 2 expect 1
check { Y->X+X->X in A some->lone A } for 2 expect 1
check { Y->X+X->X in A some->one A } for 2 expect 1
check { Y->X+X->X in A lone-> A } for 2 expect 1
check { Y->X+X->X in A lone->some A } for 2 expect 1
check { Y->X+X->X in A lone->lone A } for 2 expect 1
check { Y->X+X->X in A lone->one A } for 2 expect 1
check { Y->X+X->X in A one-> A } for 2 expect 1
check { Y->X+X->X in A one->some A } for 2 expect 1
check { Y->X+X->X in A one->lone A } for 2 expect 1
check { Y->X+X->X in A one->one A } for 2 expect 1
check { Y->X+X->Y in A -> A } for 2 expect 0
check { Y->X+X->Y in A ->some A } for 2 expect 0
check { Y->X+X->Y in A ->lone A } for 2 expect 0
check { Y->X+X->Y in A ->one A } for 2 expect 0
check { Y->X+X->Y in A some-> A } for 2 expect 0
check { Y->X+X->Y in A some->some A } for 2 expect 0
check { Y->X+X->Y in A some->lone A } for 2 expect 0
check { Y->X+X->Y in A some->one A } for 2 expect 0
check { Y->X+X->Y in A lone-> A } for 2 expect 0
check { Y->X+X->Y in A lone->some A } for 2 expect 0
check { Y->X+X->Y in A lone->lone A } for 2 expect 0
check { Y->X+X->Y in A lone->one A } for 2 expect 0
check { Y->X+X->Y in A one-> A } for 2 expect 0
check { Y->X+X->Y in A one->some A } for 2 expect 0
check { Y->X+X->Y in A one->lone A } for 2 expect 0
check { Y->X+X->Y in A one->one A } for 2 expect 0
check { Y->X+X->Y+X->X in A -> A } for 2 expect 0
check { Y->X+X->Y+X->X in A ->some A } for 2 expect 0
check { Y->X+X->Y+X->X in A ->lone A } for 2 expect 1
check { Y->X+X->Y+X->X in A ->one A } for 2 expect 1
check { Y->X+X->Y+X->X in A some-> A } for 2 expect 0
check { Y->X+X->Y+X->X in A some->some A } for 2 expect 0
check { Y->X+X->Y+X->X in A some->lone A } for 2 expect 1
check { Y->X+X->Y+X->X in A some->one A } for 2 expect 1
check { Y->X+X->Y+X->X in A lone-> A } for 2 expect 1
check { Y->X+X->Y+X->X in A lone->some A } for 2 expect 1
check { Y->X+X->Y+X->X in A lone->lone A } for 2 expect 1
check { Y->X+X->Y+X->X in A lone->one A } for 2 expect 1
check { Y->X+X->Y+X->X in A one-> A } for 2 expect 1
check { Y->X+X->Y+X->X in A one->some A } for 2 expect 1
check { Y->X+X->Y+X->X in A one->lone A } for 2 expect 1
check { Y->X+X->Y+X->X in A one->one A } for 2 expect 1
check { Y->Y in A -> A } for 2 expect 0
check { Y->Y in A ->some A } for 2 expect 1
check { Y->Y in A ->lone A } for 2 expect 0
check { Y->Y in A ->one A } for 2 expect 1
check { Y->Y in A some-> A } for 2 expect 1
check { Y->Y in A some->some A } for 2 expect 1
check { Y->Y in A some->lone A } for 2 expect 1
check { Y->Y in A some->one A } for 2 expect 1
check { Y->Y in A lone-> A } for 2 expect 0
check { Y->Y in A lone->some A } for 2 expect 1
check { Y->Y in A lone->lone A } for 2 expect 0
check { Y->Y in A lone->one A } for 2 expect 1
check { Y->Y in A one-> A } for 2 expect 1
check { Y->Y in A one->some A } for 2 expect 1
check { Y->Y in A one->lone A } for 2 expect 1
check { Y->Y in A one->one A } for 2 expect 1
check { Y->Y+X->X in A -> A } for 2 expect 0
check { Y->Y+X->X in A ->some A } for 2 expect 0
check { Y->Y+X->X in A ->lone A } for 2 expect 0
check { Y->Y+X->X in A ->one A } for 2 expect 0
check { Y->Y+X->X in A some-> A } for 2 expect 0
check { Y->Y+X->X in A some->some A } for 2 expect 0
check { Y->Y+X->X in A some->lone A } for 2 expect 0
check { Y->Y+X->X in A some->one A } for 2 expect 0
check { Y->Y+X->X in A lone-> A } for 2 expect 0
check { Y->Y+X->X in A lone->some A } for 2 expect 0
check { Y->Y+X->X in A lone->lone A } for 2 expect 0
check { Y->Y+X->X in A lone->one A } for 2 expect 0
check { Y->Y+X->X in A one-> A } for 2 expect 0
check { Y->Y+X->X in A one->some A } for 2 expect 0
check { Y->Y+X->X in A one->lone A } for 2 expect 0
check { Y->Y+X->X in A one->one A } for 2 expect 0
check { Y->Y+X->Y in A -> A } for 2 expect 0
check { Y->Y+X->Y in A ->some A } for 2 expect 0
check { Y->Y+X->Y in A ->lone A } for 2 expect 0
check { Y->Y+X->Y in A ->one A } for 2 expect 0
check { Y->Y+X->Y in A some-> A } for 2 expect 1
check { Y->Y+X->Y in A some->some A } for 2 expect 1
check { Y->Y+X->Y in A some->lone A } for 2 expect 1
check { Y->Y+X->Y in A some->one A } for 2 expect 1
check { Y->Y+X->Y in A lone-> A } for 2 expect 1
check { Y->Y+X->Y in A lone->some A } for 2 expect 1
check { Y->Y+X->Y in A lone->lone A } for 2 expect 1
check { Y->Y+X->Y in A lone->one A } for 2 expect 1
check { Y->Y+X->Y in A one-> A } for 2 expect 1
check { Y->Y+X->Y in A one->some A } for 2 expect 1
check { Y->Y+X->Y in A one->lone A } for 2 expect 1
check { Y->Y+X->Y in A one->one A } for 2 expect 1
check { Y->Y+X->Y+X->X in A -> A } for 2 expect 0
check { Y->Y+X->Y+X->X in A ->some A } for 2 expect 0
check { Y->Y+X->Y+X->X in A ->lone A } for 2 expect 1
check { Y->Y+X->Y+X->X in A ->one A } for 2 expect 1
check { Y->Y+X->Y+X->X in A some-> A } for 2 expect 0
check { Y->Y+X->Y+X->X in A some->some A } for 2 expect 0
check { Y->Y+X->Y+X->X in A some->lone A } for 2 expect 1
check { Y->Y+X->Y+X->X in A some->one A } for 2 expect 1
check { Y->Y+X->Y+X->X in A lone-> A } for 2 expect 1
check { Y->Y+X->Y+X->X in A lone->some A } for 2 expect 1
check { Y->Y+X->Y+X->X in A lone->lone A } for 2 expect 1
check { Y->Y+X->Y+X->X in A lone->one A } for 2 expect 1
check { Y->Y+X->Y+X->X in A one-> A } for 2 expect 1
check { Y->Y+X->Y+X->X in A one->some A } for 2 expect 1
check { Y->Y+X->Y+X->X in A one->lone A } for 2 expect 1
check { Y->Y+X->Y+X->X in A one->one A } for 2 expect 1
check { Y->Y+Y->X in A -> A } for 2 expect 0
check { Y->Y+Y->X in A ->some A } for 2 expect 1
check { Y->Y+Y->X in A ->lone A } for 2 expect 1
check { Y->Y+Y->X in A ->one A } for 2 expect 1
check { Y->Y+Y->X in A some-> A } for 2 expect 0
check { Y->Y+Y->X in A some->some A } for 2 expect 1
check { Y->Y+Y->X in A some->lone A } for 2 expect 1
check { Y->Y+Y->X in A some->one A } for 2 expect 1
check { Y->Y+Y->X in A lone-> A } for 2 expect 0
check { Y->Y+Y->X in A lone->some A } for 2 expect 1
check { Y->Y+Y->X in A lone->lone A } for 2 expect 1
check { Y->Y+Y->X in A lone->one A } for 2 expect 1
check { Y->Y+Y->X in A one-> A } for 2 expect 0
check { Y->Y+Y->X in A one->some A } for 2 expect 1
check { Y->Y+Y->X in A one->lone A } for 2 expect 1
check { Y->Y+Y->X in A one->one A } for 2 expect 1
check { Y->Y+Y->X+X->X in A -> A } for 2 expect 0
check { Y->Y+Y->X+X->X in A ->some A } for 2 expect 0
check { Y->Y+Y->X+X->X in A ->lone A } for 2 expect 1
check { Y->Y+Y->X+X->X in A ->one A } for 2 expect 1
check { Y->Y+Y->X+X->X in A some-> A } for 2 expect 0
check { Y->Y+Y->X+X->X in A some->some A } for 2 expect 0
check { Y->Y+Y->X+X->X in A some->lone A } for 2 expect 1
check { Y->Y+Y->X+X->X in A some->one A } for 2 expect 1
check { Y->Y+Y->X+X->X in A lone-> A } for 2 expect 1
check { Y->Y+Y->X+X->X in A lone->some A } for 2 expect 1
check { Y->Y+Y->X+X->X in A lone->lone A } for 2 expect 1
check { Y->Y+Y->X+X->X in A lone->one A } for 2 expect 1
check { Y->Y+Y->X+X->X in A one-> A } for 2 expect 1
check { Y->Y+Y->X+X->X in A one->some A } for 2 expect 1
check { Y->Y+Y->X+X->X in A one->lone A } for 2 expect 1
check { Y->Y+Y->X+X->X in A one->one A } for 2 expect 1
check { Y->Y+Y->X+X->Y in A -> A } for 2 expect 0
check { Y->Y+Y->X+X->Y in A ->some A } for 2 expect 0
check { Y->Y+Y->X+X->Y in A ->lone A } for 2 expect 1
check { Y->Y+Y->X+X->Y in A ->one A } for 2 expect 1
check { Y->Y+Y->X+X->Y in A some-> A } for 2 expect 0
check { Y->Y+Y->X+X->Y in A some->some A } for 2 expect 0
check { Y->Y+Y->X+X->Y in A some->lone A } for 2 expect 1
check { Y->Y+Y->X+X->Y in A some->one A } for 2 expect 1
check { Y->Y+Y->X+X->Y in A lone-> A } for 2 expect 1
check { Y->Y+Y->X+X->Y in A lone->some A } for 2 expect 1
check { Y->Y+Y->X+X->Y in A lone->lone A } for 2 expect 1
check { Y->Y+Y->X+X->Y in A lone->one A } for 2 expect 1
check { Y->Y+Y->X+X->Y in A one-> A } for 2 expect 1
check { Y->Y+Y->X+X->Y in A one->some A } for 2 expect 1
check { Y->Y+Y->X+X->Y in A one->lone A } for 2 expect 1
check { Y->Y+Y->X+X->Y in A one->one A } for 2 expect 1
check { Y->Y+Y->X+X->Y+X->X in A -> A } for 2 expect 0
check { Y->Y+Y->X+X->Y+X->X in A ->some A } for 2 expect 0
check { Y->Y+Y->X+X->Y+X->X in A ->lone A } for 2 expect 1
check { Y->Y+Y->X+X->Y+X->X in A ->one A } for 2 expect 1
check { Y->Y+Y->X+X->Y+X->X in A some-> A } for 2 expect 0
check { Y->Y+Y->X+X->Y+X->X in A some->some A } for 2 expect 0
check { Y->Y+Y->X+X->Y+X->X in A some->lone A } for 2 expect 1
check { Y->Y+Y->X+X->Y+X->X in A some->one A } for 2 expect 1
check { Y->Y+Y->X+X->Y+X->X in A lone-> A } for 2 expect 1
check { Y->Y+Y->X+X->Y+X->X in A lone->some A } for 2 expect 1
check { Y->Y+Y->X+X->Y+X->X in A lone->lone A } for 2 expect 1
check { Y->Y+Y->X+X->Y+X->X in A lone->one A } for 2 expect 1
check { Y->Y+Y->X+X->Y+X->X in A one-> A } for 2 expect 1
check { Y->Y+Y->X+X->Y+X->X in A one->some A } for 2 expect 1
check { Y->Y+Y->X+X->Y+X->X in A one->lone A } for 2 expect 1
check { Y->Y+Y->X+X->Y+X->X in A one->one A } for 2 expect 1
